---
image: python:latest

variables:
  PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
cache:
  paths:
  - ${PRE_COMMIT_HOME}

test:
  script:
  - pip install pre-commit
  - pre-commit install
  - pre-commit run --all-files
